### ISSUE TITLE
Question: Can custom names be used?

### ISSUE THREAD

**Issue by TechnoSchnauzer** [Goldorion/Custom-Creative-Tabs#3]
I would like to use this to make a creative inventory tab that could store Custom Texture Items, but I'm also not sure if that's possible and if it is I don't know how to do it.
If it is possible but not yet implemented, I would suggest it.

**Comment by Goldorion** [comment]
Read the MCreator's wiki.

**Comment by TechnoSchnauzer** [comment]
Can I request a little more direction? I wasn't aware this mod was directly associated with MCreator and I also don't know what I'd be looking for on the wiki. I did look at it, wasn't able to find information so hoping you can give me a little more direction so I can find what you think I need.
